// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWrGHzCBS-0rVk5JXoVkU7O-63mkdwNc',
    appId: '1:255258755366:web:a22ced8aa4d1cd0f71c1e7',
    messagingSenderId: '255258755366',
    projectId: 'ktea-6274c',
    authDomain: 'ktea-6274c.firebaseapp.com',
    storageBucket: 'ktea-6274c.appspot.com',
    measurementId: 'G-ZGPSCFJNGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgE1TaK8zmJXfLAOfv4hi1v57f7qMhgg',
    appId: '1:255258755366:android:de30983b2b492bfc71c1e7',
    messagingSenderId: '255258755366',
    projectId: 'ktea-6274c',
    storageBucket: 'ktea-6274c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCahhfMLcyrPJmi8e_xSql3RmEB4DR8rxQ',
    appId: '1:255258755366:ios:8222b9522fae554c71c1e7',
    messagingSenderId: '255258755366',
    projectId: 'ktea-6274c',
    storageBucket: 'ktea-6274c.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCahhfMLcyrPJmi8e_xSql3RmEB4DR8rxQ',
    appId: '1:255258755366:ios:a9c08dd53b4f2e1c71c1e7',
    messagingSenderId: '255258755366',
    projectId: 'ktea-6274c',
    storageBucket: 'ktea-6274c.appspot.com',
    iosBundleId: 'com.example.furnitureApp.RunnerTests',
  );
}
